<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfhg76s\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfhg76s/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPfhg76s.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPfhg76s\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPfhg76s\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Pfhg76s',
    'container.build_id' => '8f593d06',
    'container.build_time' => 1593698204,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfhg76s');
